// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEqOasQe8JJy8NjEV8jpZfjN2vsaQV2DU',
    appId: '1:707728049382:web:9bda95856ef2837bb8e727',
    messagingSenderId: '707728049382',
    projectId: 'chatapplication-97d0d',
    authDomain: 'chatapplication-97d0d.firebaseapp.com',
    storageBucket: 'chatapplication-97d0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjFROeTCHa6QlVsn1-myASGumkwhd1Cq4',
    appId: '1:707728049382:android:9be72abed546202eb8e727',
    messagingSenderId: '707728049382',
    projectId: 'chatapplication-97d0d',
    storageBucket: 'chatapplication-97d0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBPNsMZqfEMmP4k1u6AZf5kMCAc7MMlxg',
    appId: '1:707728049382:ios:2f5ce9b8c67efde1b8e727',
    messagingSenderId: '707728049382',
    projectId: 'chatapplication-97d0d',
    storageBucket: 'chatapplication-97d0d.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBPNsMZqfEMmP4k1u6AZf5kMCAc7MMlxg',
    appId: '1:707728049382:ios:2f5ce9b8c67efde1b8e727',
    messagingSenderId: '707728049382',
    projectId: 'chatapplication-97d0d',
    storageBucket: 'chatapplication-97d0d.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEqOasQe8JJy8NjEV8jpZfjN2vsaQV2DU',
    appId: '1:707728049382:web:fe68b4e62070f5c9b8e727',
    messagingSenderId: '707728049382',
    projectId: 'chatapplication-97d0d',
    authDomain: 'chatapplication-97d0d.firebaseapp.com',
    storageBucket: 'chatapplication-97d0d.appspot.com',
  );
}
